let installPrompt;
const installButton=document.getElementById('install-app');
const status=document.getElementById('install-status');
async function requestInstall(){
 if(!installPrompt){if(status)status.textContent='Use Chrome menu → Install app / Add to Home screen.';return;}
 try{await installPrompt.prompt();const choice=await installPrompt.userChoice;if(status)status.textContent=choice.outcome==='accepted'?'Installation requested. Look for My Wallet on your home screen.':'You can install later from the browser menu.';}catch{if(status)status.textContent='Use Chrome menu → Install app / Add to Home screen.';}finally{installPrompt=null;}
}
if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{if(status)status.textContent='Installation is unavailable right now. You can still continue in your browser.';});
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;if(installButton)installButton.textContent='Install My Wallet';if(!document.getElementById('quick-install')){const box=document.createElement('div');box.id='quick-install';box.innerHTML='<strong>Install My Wallet</strong><span>Add it to your home screen for one-tap access.</span><button id="quick-install-button">Install</button><button id="quick-install-close" aria-label="Close">×</button>';document.body.append(box);box.querySelector('#quick-install-button').onclick=requestInstall;box.querySelector('#quick-install-close').onclick=()=>box.remove();}});
installButton?.addEventListener('click',async()=>{if(!installPrompt){status.textContent='Follow the instructions below for your phone. Installation options depend on your browser.';document.getElementById('install-help').scrollIntoView({behavior:'smooth',block:'nearest'});return;}installButton.disabled=true;await requestInstall();installButton.disabled=false;});
window.addEventListener('appinstalled',()=>{if(status)status.textContent='My Wallet is installed. Open it from your home screen.';if(installButton)installButton.hidden=true;installPrompt=null;});
setTimeout(()=>{if(document.getElementById('quick-install')||matchMedia('(display-mode: standalone)').matches)return;const box=document.createElement('div');box.id='quick-install';box.innerHTML='<strong>Install My Wallet</strong><span>Chrome menu → Install app / Add to Home screen.</span><button id="quick-install-button">Install</button><button id="quick-install-close" aria-label="Close">×</button>';document.body.append(box);box.querySelector('#quick-install-button').onclick=requestInstall;box.querySelector('#quick-install-close').onclick=()=>box.remove();},2500);
